version: '3'

services:
  api-service:
    build: ./api
    volumes:
      - ./api:/usr/src/app
    ports:
      - 5001:80
    depends_on:
      - web

  website:
    image: php:apache
    volumes:
      - ./website:/var/www/html
    ports:
      - 5000:80
    depends_on:
      - api-service

  web:
    build: ./
    command: python3 -u flask_brevets.py
    ports:
      - "5002:5000"
    environment:
      MONGODB_HOSTNAME: brevets_mongodb
    volumes:
      - .:/brevets
    links:
      - db

  db:
    image: mongo:7.0.2
    hostname: "brevets_mongodb"

