services:
  web:
    build: .
    command: python3 -u flask_brevets.py  # Just the command and script name
    ports:
      - "5000:5000"
    environment:
      MONGODB_HOSTNAME: brevets_mongodb
    volumes:
      - .:/brevets
    links:
      - db
  db:
    image: mongo:7.0.2
    hostname: "brevets_mongodb"

